// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV466O2MYEglS_tvCPc9ZCBObgtAkvefg',
    appId: '1:135491407584:web:e99229ea4e815dda5b4a85',
    messagingSenderId: '135491407584',
    projectId: 'e-commerce-ee640',
    authDomain: 'e-commerce-ee640.firebaseapp.com',
    storageBucket: 'e-commerce-ee640.appspot.com',
    measurementId: 'G-5RHJB4V9RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8l3LVkyJ1PXndJh3r5Y0h3sMSOuuV_X4',
    appId: '1:135491407584:android:1f1616295d028d025b4a85',
    messagingSenderId: '135491407584',
    projectId: 'e-commerce-ee640',
    storageBucket: 'e-commerce-ee640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNsQAqI7SUeDs8vruWrGbArir_ZtJYFI',
    appId: '1:135491407584:ios:1bcf650d2e6023495b4a85',
    messagingSenderId: '135491407584',
    projectId: 'e-commerce-ee640',
    storageBucket: 'e-commerce-ee640.appspot.com',
    iosClientId: '135491407584-htbln7vrsf5ph9uov0ntn4a79o74qj5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNsQAqI7SUeDs8vruWrGbArir_ZtJYFI',
    appId: '1:135491407584:ios:0b4890974c9730d95b4a85',
    messagingSenderId: '135491407584',
    projectId: 'e-commerce-ee640',
    storageBucket: 'e-commerce-ee640.appspot.com',
    iosClientId: '135491407584-ho698pvs7sei0djg7evmrm2s9p43l7ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp1.RunnerTests',
  );
}
